version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD} # get the values from .env file
      POSTFRES_DB: ${DB_NAME} # get the values from .env file
    container_name: tesladb
    volumes:
      - ./postgres:/var/lib/postgresql/data # place where the data its being written in the container